[env:bt_billboard]
platform  = espressif32
board     = esp32-c3-devkitm-1
framework = arduino

board_build.partitions = min_spiffs.csv

monitor_speed  = 115200
upload_speed   = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_deps =
    majicdesigns/MD_Parola     @ ^3.7.3
    majicdesigns/MD_MAX72XX    @ ^3.5.1
    adafruit/RTClib            @ ^2.1.4
    tzapu/WiFiManager          @ ^2.0.17
    links2004/WebSockets       @ ^2.4.1